config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  resources :redbuses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/redbus.rb
class Redbus < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
       redbuses_url
    end
    def after_sign_out_path_for(resource)
        redbuses_url
    end
end

app/controllers/redbuses_controller.rb
class RedbusesController < ApplicationController
  before_action :set_redbus, only: %i[ show edit update destroy ]

  # GET /redbuses or /redbuses.json
  def index
    @redbuses = Redbus.all
  end

  # GET /redbuses/1 or /redbuses/1.json
  def show
  end

  # GET /redbuses/new
  def new
    @redbus = Redbus.new
  end

  # GET /redbuses/1/edit
  def edit
  end

  # POST /redbuses or /redbuses.json
  def create
    @redbus = Redbus.new(redbus_params)

    respond_to do |format|
      if @redbus.save
        format.html { redirect_to redbus_url(@redbus), notice: "Redbus was successfully created." }
        format.json { render :show, status: :created, location: @redbus }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @redbus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /redbuses/1 or /redbuses/1.json
  def update
    respond_to do |format|
      if @redbus.update(redbus_params)
        format.html { redirect_to redbus_url(@redbus), notice: "Redbus was successfully updated." }
        format.json { render :show, status: :ok, location: @redbus }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @redbus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redbuses/1 or /redbuses/1.json
  def destroy
    @redbus.destroy

    respond_to do |format|
      format.html { redirect_to redbuses_url, notice: "Redbus was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_redbus
      @redbus = Redbus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def redbus_params
      params.require(:redbus).permit(:name, :account, :offers)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/redbuses_helper.rb
module RedbusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-text float-right">
<% if admin_user_signed_in? %>
  Logged in as <strong><%= current_admin_user.email %></strong>.
  <%= link_to 'Edit profile', edit_admin_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_admin_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_admin_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_admin_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
    
  </body>
</html>

app/views/redbuses/_form.html.erb
<%= form_with(model: redbus, local: true) do |form| %>
  <% if redbus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(redbus.errors.count, "error") %> prohibited this redbus from being saved:</h2>

      <ul>
        <% redbus.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :account %>
    <%= form.number_field :account %>
  </div>

  <div class="field">
    <%= form.label :offers %>
    <%= form.text_field :offers %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/redbuses/edit.html.erb
<h1>Editing Redbus</h1>

<%= render 'form', redbus: @redbus %>

<%= link_to 'Show', @redbus %> |
<%= link_to 'Back', redbuses_path %>

app/views/redbuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Redbuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Account</th>
      <th>Offers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @redbuses.each do |redbus| %>
      <tr>
        <td><%= redbus.name %></td>
        <td><%= redbus.account %></td>
        <td><%= redbus.offers %></td>
        <td><%= link_to 'Show', redbus %></td>
        <td><%= link_to 'Edit', edit_redbus_path(redbus) %></td>
        <td><%= link_to 'Destroy', redbus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Redbus', new_redbus_path %>

app/views/redbuses/new.html.erb
<h1>New Redbus</h1>

<%= render 'form', redbus: @redbus %>

<%= link_to 'Back', redbuses_path %>

app/views/redbuses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @redbus.name %>
</p>

<p>
  <strong>Account:</strong>
  <%= @redbus.account %>
</p>

<p>
  <strong>Offers:</strong>
  <%= @redbus.offers %>
</p>

<%= link_to 'Edit', edit_redbus_path(@redbus) %> |
<%= link_to 'Back', redbuses_path %>